Repository lextdev/lext, pull requests merged in 2024-04, with the labels that each got.

#32 ✨ feat: added checkbox component and vscode snippets
  .husky/pre-commit
  apps/anatolia/App.tsx
  apps/anatolia/babel.config.js
  apps/anatolia/components/Main.tsx
  apps/anatolia/index.js
  apps/anatolia/metro.config.js
  apps/anatolia/package.json
  package-lock.json
  package.json
  packages/core/src/components/form/Checkbox/Checkbox.tsx
  packages/core/src/components/index.ts
  packages/core/src/interfaces/ThemeComponentInterface/ThemeComponentInterface.ts
  packages/core/src/interfaces/ThemeInterface/ThemeInterface.ts
  packages/core/src/styles/CreateStyle/CreateStyle.ts
  packages/core/src/styles/ThemeDefaultData/ThemeDefaultData.ts
Labels: enhancement

#37 🐛 fix: button background-color, border-color and color
  CHANGELOG.md
  apps/anatolia/App.tsx
  apps/anatolia/components/Main.tsx
  apps/anatolia/package.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/components/button/Button/Button.tsx
  packages/core/src/interfaces/ComponentProps/ComponentProps.ts
  packages/form/package.json
  packages/hook/package.json
  packages/storage/package.json
Labels: bug

#39 ✨ feat: image-background component added
  CHANGELOG.md
  apps/anatolia/App.tsx
  apps/anatolia/components/Main.tsx
  apps/anatolia/package.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/components/button/Button/Button.tsx
  packages/core/src/components/index.ts
  packages/core/src/components/mics/ImageBackground/ImageBackground.tsx
  packages/form/package.json
  packages/hook/package.json
  packages/storage/package.json
Labels: bug, enhancement

#43 Fix/42
  CHANGELOG.md
  apps/anatolia/package.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/components/form/Select/Select.tsx
  packages/core/src/interfaces/ComponentProps/ComponentProps.ts
  packages/form/package.json
  packages/hook/package.json
  packages/storage/package.json
Labels: bug

#45 ✨ feat: sheet component added
  CHANGELOG.md
  CONTRIBUTING.md
  apps/anatolia/babel.config.js
  apps/anatolia/components/Main.tsx
  apps/anatolia/package.json
  package-lock.json
  package.json
  packages/core/package.json
  packages/core/src/components/form/Checkbox/Checkbox.tsx
  packages/core/src/components/index.ts
  packages/core/src/components/mics/BottomSheet/BottomSheet.tsx
  packages/core/src/components/mics/Sheet/Sheet.tsx
  packages/core/src/index.ts
  packages/core/src/interfaces/ComponentProps/ComponentProps.ts
  packages/core/src/interfaces/ThemeComponentInterface/ThemeComponentInterface.ts
  packages/core/src/interfaces/ThemeInterface/ThemeInterface.ts
  packages/core/src/plugins/index.ts
  packages/core/src/styles/CreateStyle/CreateStyle.ts
  packages/core/src/styles/ThemeDefaultData/ThemeDefaultData.ts
  packages/core/src/types/SheetRef/SheetRef.ts
  packages/core/src/types/index.ts
  packages/form/package.json
  packages/hook/package.json
  packages/storage/package.json
  packages/storage/src/providers/SessionProvider/SessionProvider.tsx
Labels: bug, enhancement, dependencies
